version: "2"
services:
  app:
    container_name: app
    restart: always
    environment:
      MONGO_CONNECTION: mongodb://mongo:27017/local
      NODE_ENV: production
    build: .
    volumes:
    - ".:/usr/src/app"
    ports:
    - "3003:3000"
    links:
    - mongo
  mongo:
    container_name: mongo
    image: mongo
#    volumes:
#    - ./data:/data/db
    ports:
    - "27017:27017"
